// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.4
// source: chaincode_event.proto

package ppeer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChaincodeEvent 结构体用于表示与 chaincode 相关的事件和注册信息。通过使用 ChaincodeEvent 结构体，可以在链码
// 中定义和触发特定的事件，并通过有效载荷传递相关数据。这使得链码在执行特定操作时能够通知其他链码或外部系统。
type ChaincodeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ChaincodeId 表示与事件相关的 chaincode 的标识符。
	ChaincodeId string `protobuf:"bytes,1,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	// TxId 表示与事件相关的的交易标识符。
	TxId string `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// EventName 表示事件的名称。
	EventName string `protobuf:"bytes,3,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Payload 表示事件的有效载荷。
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ChaincodeEvent) Reset() {
	*x = ChaincodeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chaincode_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChaincodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeEvent) ProtoMessage() {}

func (x *ChaincodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chaincode_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeEvent.ProtoReflect.Descriptor instead.
func (*ChaincodeEvent) Descriptor() ([]byte, []int) {
	return file_chaincode_event_proto_rawDescGZIP(), []int{0}
}

func (x *ChaincodeEvent) GetChaincodeId() string {
	if x != nil {
		return x.ChaincodeId
	}
	return ""
}

func (x *ChaincodeEvent) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *ChaincodeEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ChaincodeEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_chaincode_event_proto protoreflect.FileDescriptor

var file_chaincode_event_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x70, 0x65, 0x65, 0x72, 0x22, 0x81,
	0x01, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x31, 0x31, 0x30, 0x39, 0x30, 0x38, 0x31, 0x35, 0x2f, 0x6d, 0x61, 0x79, 0x79, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x70, 0x65, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chaincode_event_proto_rawDescOnce sync.Once
	file_chaincode_event_proto_rawDescData = file_chaincode_event_proto_rawDesc
)

func file_chaincode_event_proto_rawDescGZIP() []byte {
	file_chaincode_event_proto_rawDescOnce.Do(func() {
		file_chaincode_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_chaincode_event_proto_rawDescData)
	})
	return file_chaincode_event_proto_rawDescData
}

var file_chaincode_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chaincode_event_proto_goTypes = []interface{}{
	(*ChaincodeEvent)(nil), // 0: ppeer.ChaincodeEvent
}
var file_chaincode_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chaincode_event_proto_init() }
func file_chaincode_event_proto_init() {
	if File_chaincode_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chaincode_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChaincodeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chaincode_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chaincode_event_proto_goTypes,
		DependencyIndexes: file_chaincode_event_proto_depIdxs,
		MessageInfos:      file_chaincode_event_proto_msgTypes,
	}.Build()
	File_chaincode_event_proto = out.File
	file_chaincode_event_proto_rawDesc = nil
	file_chaincode_event_proto_goTypes = nil
	file_chaincode_event_proto_depIdxs = nil
}
